### ISSUE TITLE
Broken link to OKR page

### ISSUE THREAD

**Issue by netapp-bcammett** [MicrosoftDocs/microsoft-style-guide#372]
The link to the OKR page is broken:
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/bojectives-and-key-results-(OKR)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c33cc66-057c-fc38-363b-3eb9e09b131a
* Version Independent ID: f9680f41-fde0-77de-63dc-badc606d7273
* Content: [What's new? - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/welcome/whats-new)
* Content Source: [styleguide/welcome/whats-new.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/whats-new.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by chanakavp** [comment]
Correct link: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/objectives-and-key-results-(okr)

**Comment by S-LRaillard** [comment]
@chanakavp Sorry about that ! these have been fixed.

**Comment by chanakavp** [comment]
Still broken to me. https://learn.microsoft.com/en-us/style-guide/welcome/whats-new

**Comment by S-LRaillard** [comment]
Hi there,
Sorry about that - somehow the pull request got messed up, so the change was only showing up in staging - I think it should resolve within an hour or so now that I fixed the PR.
